# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE:
  - REPOSITORY
  - JSON
  - JAVASCRIPT
  - CSS
  - HTML
  - COPYPASTE
DISABLE_LINTERS:
  - YAML_V8R
  - SPELL_LYCHEE
PRINT_ALL_FILES: false
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3008 --ignore DL4006 --ignore DL3009 --ignore DL3059"
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: true
EMAIL_REPORTER: false
FILEIO_REPORTER: false
