language: ruby
rvm:
  - 2.5.0
  
before_script:
 - chmod +x ./scripts/cibuild # or do this locally and commit
script: ./scripts/cibuild
after_success: s3_website push


branches:
  only:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
