title: JKAN
description: A lightweight, backend-free open data portal, powered by Jekyll.
baseurl: /jkan

# Authentication
github_client_id: 
gatekeeper_host: 

# Dataset schema
schema: default

# Categories
category_list:
  - Arts / Culture / History
  - Budget / Finance
  - Economy
  - Education
  - Elections / Politics
  - Environment
  - Food
  - Health / Human Services
  - Parks / Recreation
  - Planning / Zoning
  - Public Safety
  - Real Estate / Land Records
  - Transportation
  - Uncategorized

# Link for the "fork me on github" banner. Remove this line to suppress banner.
fork_me_url: https://github.com/timwis/jkan

# Nav bar
navigation:
  - title: Datasets
    url: /datasets/

# Collections
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  organizations:
    output: false

# Collections (cont'd)
defaults:
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - node_modules
  - scripts/src
  - package.json
  - webpack.config.js
  - README.md
  - LICENSE
