# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:
  - field_name: title
    label: Titolo
    datajson: title
  - field_name: organization
    label: Organizzazione
    form_template: form/organization.html
    datajson: publisher.name
  - field_name: notes
    label: Descrizione
    form_template: form/textarea.html
    datajson: description
  - field_name: license
    label: License
    form_template: form/license.html
    datajson: license
  - field_name: category
    label: Categoria
    form_template: form/category.html
    display_template: display/category.html
    datajson: category
  - field_name: maintainer
    label: Manutentore
    datajson: contactPoint.fn
  - field_name: maintainer_email
    label: Email Manutentore
    datajson: contactPoint.hasEmail

resource_fields:
  - field_name: name
    label: Nome Risorsa
    datajson: distribution.title
  - field_name: url
    label: URL
    datajson: distribution.downloadURL
  - field_name: format
    label: Formato
    datajson: distribution.format
    form_template: form/dropdown.html
    values:
      - api
      - csv
      - json
      - geojson
      - html
      - kml
      - kmz
      - shp
      - xml
      - osm
      - pbf

organization_fields:
  - field_name: title
    label: Titolo
  - field_name: description
    label: Descrizione
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html
